# Generated by Django 5.0.6 on 2024-05-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='report',
            name='certificate_id',
            field=models.IntegerField(help_text='Enter the certificate ID if this report is about a certificate eg., 941'),
        ),
    ]
